services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'gitlab'
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - ts-net
  
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    hostname: 'nexus'
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - ts-net

networks:
  ts-net:
    driver: bridge


volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  nexus_data:


